"""
Display geometry and frame packing, shared by the video converter and the tests.

This is the one place the segment rectangles are written down on the software
side. They mirror `src/multi_seg_monitor.v` and SPEC.md section 1.1 -- if the RTL
layout changes, change it here too or the round-trip test will say so.
"""

# Grid -- 800x600 mode, with the fat glyph: shapes.digit(thick_h=4, len_h=5,
# thick_v=4, len_v=4, gap_x=2, gap_y=2), which is where every number below
# comes from.  `python3 tools/shapes.py` prints them.
COLS, ROWS = 53, 27
CELL_W, CELL_H = 15, 22
MARGIN_X = 2  # (800 - COLS*CELL_W) / 2
MARGIN_Y = 3  # (600 - ROWS*CELL_H) / 2 -- neither divides evenly any more
GRID_W = COLS * CELL_W  # 795
GRID_H = ROWS * CELL_H  # 594

BYTES_PER_DIGIT = 4
ROW_BYTES = COLS * BYTES_PER_DIGIT  # 212; the line buffer's wall is 64 columns
FRAME_BYTES = ROWS * ROW_BYTES  # 5724

# Colour palettes -- mirrors src/palette.v and src/palette_presets.v the same
# way SEGMENTS mirrors the RTL's segment zones. test_multi_seg.py compares the
# RTL against curve_value() below, bit for bit.
#
# A palette is not a 16-entry table any more but three per-channel curves,
# because a loadable 16x12-bit table costs 192 flops -- about 40% of the
# die's free area -- where a curve costs 18 bits per channel. Each channel is
# two straight lines: from (0, 0) to a knee (x1, y1), then on through a
# second point (x2, y2) until it clips at 15. The clip is load-bearing: it is
# what gives the tinted ramps their flat top without a third segment.
#
# The hardware doesn't store the points, it stores the knee plus two slopes
# in eighths (5 bits each, 0-3.875) -- curve_params() converts. The points
# are what a person edits (tools/palette_builder), the slopes are what the
# chip multiplies by, and curve_value() is exactly the RTL's arithmetic
# including its rounding, so the tool always shows what the chip will draw.
#
# The 8 built-in palettes live in tools/palette_builder/presets.json, which
# is the source of truth for both this module and src/palette_presets.v
# (regenerated by `palette_builder.py --write-rtl`). Preset 0 is the plain
# grey ramp (R=G=B=index), byte-identical to the old direct-to-DAC mapping,
# so the ungraded gold images and round-trip tests don't change.
#
# There used to be a single-channel gamma LUT here (src/gamma.v, removed):
# the PmodVGA output is a hard 4-bit DAC, 16 codes in and 16 codes out, and
# any monotonic curve reshaping 16 values into 16 values is forced by
# pigeonhole into being the identity -- a non-trivial curve can only ever
# collide two stored indices onto the same code, which is what made indices
# 14 and 15 genuinely indistinguishable on hardware (dithering_investigation.md
# on the gamma-dithering branch). The knee reintroduces a curve on purpose,
# for per-monitor gamma shaping, and pigeonhole still applies to it: what it
# buys is a choice of where the collisions land, not a way round them.
#
# Rules checked by verify_palettes() below and tools/test_palettes.py:
#   1. Entry 0 is (0, 0, 0) -- index 0 is used both for an explicitly-zeroed
#      segment and every non-segment background/margin pixel, so a palette
#      that colours it would tint the whole background, not just dim a
#      segment. (src/palette.v also forces this in hardware, so a hand-rolled
#      config packet can't break it either.)
#   2. Brightness (r+g+b) never decreases with the index, so a brighter
#      stored level never looks dimmer.
#   3. Entries 1-15 are pairwise distinct. Grey must also differ from entry 0
#      everywhere; a tinted preset may set entry 1 to black too (a designed
#      dark floor: stored level 1 is then indistinguishable from off, 15
#      distinct levels, not 16), or use all 16 -- either is legal.
#
# Deliberately NOT a rule: surviving Tiny VGA's 2-bit/channel truncation
# (src/tt_um_multi_seg_monitor.v keeps each channel's top 2 bits). A smooth
# single-hue ramp cannot, so on the Tiny VGA Pmod the tinted palettes show
# 7-10 distinct levels and grey 4.

import json as _json
import os as _os

PRESETS_JSON = _os.path.join(
    _os.path.dirname(_os.path.abspath(__file__)), "palette_builder", "presets.json"
)
N_PRESETS = 8
SLOPE_MAX = 31  # 5-bit slope, in eighths


def _rdiv(a, b):
    """a / b rounded half up, for non-negative integers."""
    return (2 * a + b) // (2 * b)


def curve_params(x1, y1, x2, y2):
    """Two points -> the (knee_x, knee_y, m1, m2) the hardware stores.

    Raises ValueError for a curve the hardware can't draw or the rules forbid:
    the knee must leave entry 0 black, and the second point must lie to the
    right of the knee and not below it (the chip has no negative slopes)."""
    for v in (x1, y1, x2, y2):
        if not (isinstance(v, int) and 0 <= v <= 15):
            raise ValueError(f"curve point value {v!r} is not an integer 0-15")
    if x1 == 0 and y1 != 0:
        raise ValueError("a knee at x=0 must have y=0, or entry 0 isn't black")
    if x2 <= x1:
        raise ValueError(f"second point x={x2} must be right of the knee x={x1}")
    if y2 < y1:
        raise ValueError(f"second point y={y2} is below the knee y={y1}")
    m1 = min(SLOPE_MAX, _rdiv(y1 * 8, x1)) if x1 else 0
    m2 = min(SLOPE_MAX, _rdiv((y2 - y1) * 8, x2 - x1))
    return x1, y1, m1, m2


def curve_value(idx, knee_x, knee_y, m1, m2):
    """One channel of src/palette.v, bit for bit: slopes in eighths, rounded
    half up, clipped at 15. Index 0 is forced black, as the RTL does."""
    if idx == 0:
        return 0
    if idx < knee_x:
        v = (m1 * idx + 4) >> 3
    else:
        v = ((knee_y << 3) + m2 * (idx - knee_x) + 4) >> 3
    return min(15, v)


def curve_palette(params):
    """((kx, ky, m1, m2) for r, g, b) -> 16 (r, g, b) entries."""
    chans = [[curve_value(i, *p) for i in range(16)] for p in params]
    return list(zip(*chans))


def points_to_params(preset):
    """A presets.json entry -> hardware params for (r, g, b)."""
    return tuple(curve_params(*preset[ch]) for ch in "rgb")


def pack_params(params):
    """Hardware params for (r, g, b) -> the 54-bit word src/palette.v takes:
    {R, G, B}, each channel {knee_x[3:0], knee_y[3:0], m1[4:0], m2[4:0]}."""
    word = 0
    for kx, ky, m1, m2 in params:
        word = (word << 18) | (kx << 14) | (ky << 10) | (m1 << 5) | m2
    return word


def unpack_params(word):
    out = []
    for shift in (36, 18, 0):
        ch = (word >> shift) & 0x3FFFF
        out.append(((ch >> 14) & 0xF, (ch >> 10) & 0xF, (ch >> 5) & 0x1F, ch & 0x1F))
    return tuple(out)


# Config packet (src/multi_seg_monitor.v): sent while uio[7] is low, one byte
# per strobe. Byte 0 is a header whose top nibble must be CONFIG_MAGIC or the
# chip ignores the rest of the packet; bytes 1-9 are the curve, 3 per channel
# (R, G, B): {knee_x, knee_y}, then m1, then m2.
CONFIG_MAGIC = 0xA
CFG_PMOD = 1 << 0
CFG_CYCLE = 1 << 2
CFG_LOAD_PRESET = 1 << 3


def config_packet(params=None, pmod_type=0, cycle=False):
    """Bytes for one config packet. With `params` None the header alone is
    sent with load_preset set, which puts the strapped preset back."""
    header = (CONFIG_MAGIC << 4) | (CFG_PMOD if pmod_type else 0) | (CFG_CYCLE if cycle else 0)
    if params is None:
        return bytes([header | CFG_LOAD_PRESET])
    body = []
    for kx, ky, m1, m2 in params:
        body += [(kx << 4) | ky, m1, m2]
    return bytes([header] + body)


def load_presets(path=PRESETS_JSON):
    """presets.json -> list of {name, r, g, b} dicts (points, not params)."""
    with open(path) as f:
        presets = _json.load(f)["presets"]
    if len(presets) != N_PRESETS:
        raise ValueError(f"{path} holds {len(presets)} presets, the chip has {N_PRESETS}")
    return presets


PRESETS = load_presets()
PRESET_PARAMS = [points_to_params(p) for p in PRESETS]
PALETTES = [curve_palette(p) for p in PRESET_PARAMS]

PRESETS_V = _os.path.join(
    _os.path.dirname(_os.path.abspath(__file__)), "..", "src", "palette_presets.v"
)


def presets_verilog(presets=None):
    """src/palette_presets.v's full text, generated from presets.json.
    tools/test_palettes.py fails if the checked-in file differs from this."""
    if presets is None:
        presets = PRESETS
    lines = [
        "`default_nettype none",
        "//",
        "// GENERATED from tools/palette_builder/presets.json by",
        "// `tools/palette_builder/palette_builder.py --write-rtl` -- edit the JSON",
        "// (or use the builder), not this file. tools/test_palettes.py fails if the",
        "// two drift apart.",
        "//",
        "// The chip's 8 built-in palettes as curve parameters for src/palette.v:",
        "// {R, G, B}, each {knee_x[3:0], knee_y[3:0], m1[4:0], m2[4:0]}, slopes in",
        "// eighths. A constant table like this costs a few gates per preset, not",
        "// flops -- only the live palette in multi_seg_monitor.v is stored.",
        "//",
        "module palette_presets (",
        "    input  wire [2:0]  sel,",
        "    output reg  [53:0] params",
        "    );",
        "",
        "    always @* begin",
        "        case (sel)",
    ]
    for n, preset in enumerate(presets):
        params = points_to_params(preset)
        pts = "  ".join(f"{ch}{tuple(preset[ch])}" for ch in "rgb")
        lines.append(f"            // {n}: {preset['name']}  {pts}")
        fields = ", ".join(
            f"4'd{kx}, 4'd{ky}, 5'd{m1}, 5'd{m2}" for kx, ky, m1, m2 in params
        )
        lines.append(f"            3'd{n}: params = {{{fields}}};")
    lines += [
        "        endcase",
        "    end",
        "",
        "endmodule",
        "`default_nettype wire",
        "",
    ]
    return "\n".join(lines)


def verify_palettes(palettes=None):
    """Raises AssertionError if any palette violates the rules above."""
    if palettes is None:
        palettes = PALETTES
    for n, palette in enumerate(palettes):
        assert len(palette) == 16, f"palette {n} has {len(palette)} entries, not 16"
        for r, g, b in palette:
            assert 0 <= r <= 15 and 0 <= g <= 15 and 0 <= b <= 15, (
                f"palette {n} has an out-of-range channel value: {(r, g, b)}"
            )
        assert tuple(palette[0]) == (0, 0, 0), f"palette {n} index 0 is {palette[0]}, not black"
        lum = [sum(c) for c in palette]
        assert all(a <= b for a, b in zip(lum, lum[1:])), (
            f"palette {n} gets dimmer as the index rises: {palette}"
        )
        assert len(set(map(tuple, palette[1:]))) == 15, (
            f"palette {n} has collisions among entries 1-15"
        )
        if n == 0:
            assert len(set(map(tuple, palette))) == 16, "palette 0 must keep all 16 levels distinct"


# Segment rectangles within a cell, as (name, x0, x1, y0, y1) inclusive.
# Index order is the nibble order of a digit word: a, b, c, d, e, f, g, DP.
# The digit body is 13x20; columns 13-14 and rows 20-21 are the gaps that keep
# neighbouring digits from merging, and the decimal point lives in the first
# gap column.
SEGMENTS = [
    ("a", 4, 8, 0, 3),
    ("b", 9, 12, 4, 7),
    ("c", 9, 12, 12, 15),
    ("d", 4, 8, 16, 19),
    ("e", 0, 3, 12, 15),
    ("f", 0, 3, 4, 7),
    ("g", 4, 8, 8, 11),
    ("DP", 13, 13, 16, 19),
]

def pack_digit(intensities):
    """Eight 4-bit segment intensities -> 4 bytes, low nibble first."""
    assert len(intensities) == 8
    return bytes(
        (intensities[2 * k + 1] << 4) | (intensities[2 * k] & 0xF) for k in range(4)
    )


def unpack_digit(data):
    """4 bytes -> eight 4-bit segment intensities."""
    assert len(data) == 4
    out = []
    for byte in data:
        out.append(byte & 0xF)
        out.append(byte >> 4)
    return out


def digit_offset(col, row):
    """Byte offset of a digit within a frame."""
    return (row * COLS + col) * BYTES_PER_DIGIT


def segment_pixels(col, row, seg_index):
    """Screen pixel rectangle covered by one segment, as (x0, x1, y0, y1)."""
    _, sx0, sx1, sy0, sy1 = SEGMENTS[seg_index]
    x = MARGIN_X + col * CELL_W
    y = MARGIN_Y + row * CELL_H
    return x + sx0, x + sx1, y + sy0, y + sy1


def segment_centre(col, row, seg_index):
    """A pixel guaranteed to be inside the segment -- used for sampling."""
    x0, x1, y0, y1 = segment_pixels(col, row, seg_index)
    return (x0 + x1) // 2, (y0 + y1) // 2
